import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import SessionWrapper from "./SessionWrapper";
// import { ApolloProvider } from "@apollo/client";
// import client from "./lib/apolloClient";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Kgkraft",
  description: "Generated by create next app",
  icons: {
    icon: "/kgKraftLogo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {/* <ApolloProvider client={client}> */}
        <StoreProvider>
          <SessionWrapper>{children}</SessionWrapper>
        </StoreProvider>
        {/* </ApolloProvider> */}
      </body>
    </html>
  );
}
